// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJuyOZ-B6WiRDqinDUzvsFfcAXZR3G0-c',
    appId: '1:152576847441:web:d3b70e575799c5ff025270',
    messagingSenderId: '152576847441',
    projectId: 'fooddeliveryapp-e47a9',
    authDomain: 'fooddeliveryapp-e47a9.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-e47a9.appspot.com',
    measurementId: 'G-RN71ZFF024',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEv2dDT5MJJMv6ctg3ueMxgeDVO9HPTuY',
    appId: '1:152576847441:android:2f44af7bb10edb71025270',
    messagingSenderId: '152576847441',
    projectId: 'fooddeliveryapp-e47a9',
    storageBucket: 'fooddeliveryapp-e47a9.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJuyOZ-B6WiRDqinDUzvsFfcAXZR3G0-c',
    appId: '1:152576847441:web:2521d679bc95da96025270',
    messagingSenderId: '152576847441',
    projectId: 'fooddeliveryapp-e47a9',
    authDomain: 'fooddeliveryapp-e47a9.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-e47a9.appspot.com',
    measurementId: 'G-4GW2S5JERX',
  );
}
